/// 날짜(dayOfYear) % 30 으로 인덱스를 결정 — 하루 동안 동일 문구 유지
const Map<String, List<String>> kDailyQuotes = {
  'ko': [
    '오늘 하루도 당신의 결이 흐려지지 않기를.',
    '얼굴은 마음이 오래 머문 자리다.',
    '좋은 상(相)은 타고나는 것이 아니라 쌓아가는 것이다.',
    '눈빛이 맑으면 먼 곳까지 보인다.',
    '이마에 새겨진 선은 지나온 길의 기록이다.',
    '코끝이 부드러운 사람은 마음도 너그럽다.',
    '입매가 단정한 이는 말보다 침묵이 깊다.',
    '턱이 단단한 자에게 세월은 쉽게 무너뜨리지 못한다.',
    '눈썹 사이의 간격은 마음의 여유를 담는다.',
    '손금은 살아온 흔적이자 나아갈 방향이다.',
    '생명선이 깊은 이는 뿌리가 단단하다.',
    '감정선이 고른 사람은 관계에서 흔들리지 않는다.',
    '두뇌선이 길수록 생각이 길고 멀리 간다.',
    '운명선은 의지가 만들어가는 길이다.',
    '손 모양은 그 사람의 기질을 닮아있다.',
    '관상은 운명을 보는 게 아니라 가능성을 읽는 것이다.',
    '당신의 얼굴에는 당신만의 이야기가 있다.',
    '하늘이 준 얼굴보다 내가 만든 얼굴이 더 귀하다.',
    '봄날의 빛처럼, 오늘도 당신의 기운이 고르기를.',
    '깊은 밤에도 별은 자리를 지킨다, 당신처럼.',
    '결이 고운 사람은 지나쳐도 향기가 남는다.',
    '오늘의 표정이 내일의 상(相)을 만든다.',
    '마음이 고요하면 얼굴도 맑아진다.',
    '손바닥의 선만큼이나 당신의 길은 다양하다.',
    '천 번의 표정이 모여 하나의 인상이 된다.',
    '보이지 않는 것을 읽는 눈이 진짜 통찰이다.',
    '기운이 얼굴에 드러나기까지 시간이 걸린다.',
    '당신의 이목구비는 당신이 걸어온 길을 알고 있다.',
    '오늘 하루 좋은 기운이 당신의 결 위에 머물기를.',
    '상(相)을 바꾸고 싶다면 먼저 마음을 바꾸어라.',
  ],
  'en': [
    'May your presence stay clear and undiminished today.',
    'The face is where the heart has lingered longest.',
    'A good countenance is not born — it is built.',
    'Clear eyes see what others cannot.',
    'The lines on your brow record the roads you have walked.',
    'A gentle nose speaks of a generous spirit.',
    'Composed lips carry deeper truths than spoken words.',
    'A firm chin tells time it cannot easily win.',
    'The space between the brows holds the room a mind keeps.',
    'The palm holds the story of where you have been and where you may go.',
    'A deep life line speaks of roots that hold.',
    'An even heart line is a steady hand in every relation.',
    'The longer the head line, the farther the thought travels.',
    'The fate line is not fixed — it is forged by will.',
    'The shape of the hand echoes the nature of its owner.',
    'Face reading is not about fate — it is about possibility.',
    'Your face carries a story that belongs only to you.',
    'The face you have shaped matters more than the one you were given.',
    'Like spring light, may your energy run smooth today.',
    'Even in deep night, the stars hold their place — as you do.',
    'A person of fine character leaves a trace long after they pass.',
    'Today\'s expression is shaping tomorrow\'s impression.',
    'When the mind is still, the face grows clear.',
    'Your path is as varied as the lines on your palm.',
    'A thousand expressions gather into one lasting impression.',
    'The eye that reads what cannot be seen — that is real insight.',
    'It takes time for inner energy to surface on the face.',
    'Your features know the roads you have traveled.',
    'May good energy rest upon your presence today.',
    'To change your countenance, first change what you carry inside.',
  ],
  'ja': [
    '今日もあなたの佇まいが曇りませんように。',
    '顔とは、心が長く宿った場所である。',
    '良い相は生まれつきではなく、積み重ねで生まれる。',
    '目の光が清ければ、遠くまで見通せる。',
    '額に刻まれた線は、歩んできた道の記録だ。',
    '鼻先が柔らかな人は、心も寛大である。',
    '口元が整った人は、言葉より沈黙が深い。',
    '顎の強い者に、歳月は容易に牙を剥かない。',
    '眉間の間隔は、心の余裕を映している。',
    '手相は歩んできた跡であり、進むべき道標でもある。',
    '生命線の深い人は、根がしっかりと張っている。',
    '感情線が整う人は、関係の中で揺れない。',
    '頭脳線が長いほど、思考は遠くまで届く。',
    '運命線は意志が切り拓いていく道だ。',
    '手の形は、その人の気質に似ている。',
    '人相を見るとは、運命ではなく可能性を読むことだ。',
    'あなたの顔には、あなただけの物語がある。',
    '生まれ持った顔より、自らが作った顔の方が尊い。',
    '春の光のように、今日もあなたの気が整いますように。',
    '深夜でも星は定位置に在る、あなたのように。',
    '佇まいの美しい人は、去った後も香りが残る。',
    '今日の表情が、明日の人相を作る。',
    '心が静かならば、顔も澄んでくる。',
    '手のひらの線と同様、あなたの道も多様だ。',
    '千の表情が積み重なり、一つの印象になる。',
    '見えないものを読む眼こそ、真の洞察だ。',
    '内なる気が顔に現れるまでには時間がかかる。',
    'あなたの目鼻立ちは、歩んできた道を知っている。',
    '今日も良い気があなたの佇まいに宿りますように。',
    '相を変えたければ、まず心を変えることだ。',
  ],
  'zh': [
    '愿你今日气息清晰、心神安稳。',
    '面相，是心灵久久驻留之处。',
    '好相貌并非天生，而是日积月累而成。',
    '眼神清澈者，能望见旁人看不到的远方。',
    '额上的纹路，是走过之路的记录。',
    '鼻尖柔和之人，内心亦宽厚。',
    '唇形端正者，沉默往往比言语更深邃。',
    '下颌坚毅者，岁月难以轻易将其击溃。',
    '两眉之间的间距，容纳着内心的从容。',
    '手纹既是走过的痕迹，也是前行的方向。',
    '生命线深者，根基稳固。',
    '感情线平稳者，在关系中不易动摇。',
    '头脑线越长，思维便能走得越远。',
    '命运线并非注定，而是由意志一步步开拓。',
    '手的形状，映照着主人的气质。',
    '看面相，并非窥探命运，而是读懂可能性。',
    '你的面容，承载着只属于你的故事。',
    '自己塑造的面容，比天赐的更为珍贵。',
    '愿你今日的气场，如春光般均匀流淌。',
    '深夜里，星辰依然各守其位，如你一般。',
    '气质温润之人，离去之后仍留有余香。',
    '今日的神情，正在塑造明日的相貌。',
    '心若平静，面自清明。',
    '你的道路，如掌纹般丰富多样。',
    '千种表情汇聚，成就一种印象。',
    '能读懂无形之物的眼睛，才是真正的洞见。',
    '内在气韵浮现于面，需要时间的沉淀。',
    '你的眉眼，深知你走过的每一段路。',
    '愿今日的好气场，静静停驻在你的周身。',
    '欲改变面相，先从改变内心开始。',
  ],
};

String getDailyQuote(String locale) {
  final quotes = kDailyQuotes[locale] ?? kDailyQuotes['ko']!;
  final now = DateTime.now();
  final dayOfYear = now.difference(DateTime(now.year)).inDays;
  return quotes[dayOfYear % quotes.length];
}
